"""Emit the After Effects ExtendScript that rebuilds the shot.

Pure Python, no ``bpy`` (SPEC.md section 6). Takes plain dicts and returns a
string.

Everything emitted is ECMAScript 3 (section 7.1). In particular there is no
``JSON`` in ExtendScript, so data is written as literal ``var`` declarations
rather than serialised and parsed on the AE side.

Milestone 2 emits the comp and the camera. Importing the pass sequences,
stacking them and parenting nulls is M4.
"""

import math
import os

RUNTIME_FILENAME = "pt_runtime.jsx"
RUNTIME_DIR = "ae_runtime"

#: Layer name used for the camera, and the key for replacing it on re-run.
CAMERA_LAYER_NAME = "Blender Camera"


def runtime_path():
    """Absolute path of the bundled ExtendScript runtime."""
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), RUNTIME_DIR, RUNTIME_FILENAME)


def load_runtime():
    """Read the bundled runtime source."""
    with open(runtime_path(), encoding="utf-8") as handle:
        return handle.read()


def format_number(value):
    """Shortest representation that round-trips, and is valid ES3."""
    number = float(value)
    if not math.isfinite(number):
        raise ValueError(f"cannot emit non-finite number: {value!r}")
    if number == 0.0:
        return "0"
    text = repr(number)
    if text.endswith(".0"):
        text = text[:-2]
    return text


def js_string(text):
    """A double-quoted ES3 string literal."""
    out = []
    for char in str(text):
        if char in ('"', "\\"):
            out.append("\\" + char)
        elif char == "\n":
            out.append("\\n")
        elif char == "\r":
            out.append("\\r")
        elif char == "\t":
            out.append("\\t")
        elif ord(char) < 0x20 or ord(char) > 0x7E:
            # ExtendScript source encoding is unreliable; escape anything
            # outside printable ASCII rather than trusting the file to survive.
            out.append(f"\\u{ord(char):04x}")
        else:
            out.append(char)
    return '"' + "".join(out) + '"'


def js_number_array(values):
    return "[" + ", ".join(format_number(v) for v in values) + "]"


def js_vector_array(vectors):
    return "[" + ", ".join(js_number_array(v) for v in vectors) + "]"


def comp_duration(frame_start, frame_end, frame_rate):
    """Comp length in seconds, inclusive of both end frames."""
    return (frame_end - frame_start + 1) / float(frame_rate)


def frame_times(frame_start, frame_end, frame_rate):
    """AE times in seconds for each Blender frame."""
    return [
        (frame - frame_start) / float(frame_rate) for frame in range(frame_start, frame_end + 1)
    ]


def _collapse(values):
    """Drop a track to a single entry when nothing actually changes."""
    first = values[0]
    for value in values[1:]:
        if value != first:
            return list(values)
    return [first]


def write_jsx(comp, camera, runtime_source=None):
    """Return the complete ``.jsx`` source for one shot.

    ``comp`` needs ``name``, ``width``, ``height``, ``pixel_aspect``,
    ``frame_rate``, ``frame_start`` and ``frame_end``. ``camera`` needs
    ``name``, ``position``, ``orientation`` and ``zoom``, each a list with one
    entry per frame.
    """
    if runtime_source is None:
        runtime_source = load_runtime()

    frame_start = int(comp["frame_start"])
    frame_end = int(comp["frame_end"])
    frame_rate = float(comp["frame_rate"])
    if frame_end < frame_start:
        raise ValueError("frame_end is before frame_start")

    times = frame_times(frame_start, frame_end, frame_rate)
    positions = _collapse(camera["position"])
    orientations = _collapse(camera["orientation"])
    zooms = _collapse(camera["zoom"])

    for name, track in (("position", positions), ("orientation", orientations), ("zoom", zooms)):
        if len(track) not in (1, len(times)):
            raise ValueError(f"camera {name} has {len(track)} entries, expected 1 or {len(times)}")

    flat_zooms = [z[0] if isinstance(z, (list, tuple)) else z for z in zooms]

    lines = [
        "/*",
        " * Generated by Passthrough. Do not edit by hand -- re-export instead.",
        f" * Shot: {comp['name']}",
        f" * Frames {frame_start}-{frame_end} at {format_number(frame_rate)} fps",
        " */",
        "",
        runtime_source.rstrip(),
        "",
        "// ---- generated data ----",
        f"var PT_COMP_NAME = {js_string(comp['name'])};",
        f"var PT_WIDTH = {format_number(comp['width'])};",
        f"var PT_HEIGHT = {format_number(comp['height'])};",
        f"var PT_PIXEL_ASPECT = {format_number(comp.get('pixel_aspect', 1.0))};",
        f"var PT_FRAME_RATE = {format_number(frame_rate)};",
        f"var PT_DURATION = {format_number(comp_duration(frame_start, frame_end, frame_rate))};",
        f"var PT_CAMERA_NAME = {js_string(camera.get('name', CAMERA_LAYER_NAME))};",
        f"var PT_TIMES = {js_number_array(times)};",
        f"var PT_CAM_POSITION = {js_vector_array(positions)};",
        f"var PT_CAM_ORIENTATION = {js_vector_array(orientations)};",
        f"var PT_CAM_ZOOM = {js_number_array(flat_zooms)};",
        "",
        "// ---- build ----",
        "(function () {",
        '    app.beginUndoGroup("Passthrough import");',
        "    try {",
        "        var comp = ptEnsureComp(",
        "            PT_COMP_NAME, PT_WIDTH, PT_HEIGHT, PT_PIXEL_ASPECT,",
        "            PT_DURATION, PT_FRAME_RATE",
        "        );",
        "        comp.openInViewer();",
        "        ptAddCamera(",
        "            comp, PT_CAMERA_NAME, PT_TIMES,",
        "            PT_CAM_POSITION, PT_CAM_ORIENTATION, PT_CAM_ZOOM",
        "        );",
        "    } finally {",
        "        app.endUndoGroup();",
        "    }",
        "})();",
        "",
    ]
    return "\n".join(lines)
